version: "3.1"
services:
    postgres:
      build: 
        context: .
        dockerfile: docker/Dockerfile-db
        args:
          - "FILENAME=${FILENAME}"
          - "FILENAMECORE=${FILENAMECORE}"
      secrets:
        - db_password
        - db_username
      volumes:
        - pg_data:/var/lib/postgresql/9.5/main
    
    backend:
      build:
        context: .
        dockerfile: docker/Dockerfile-backend
      depends_on:
        - postgres
      volumes:
        - static_backend:/home/iftttuser/iot-tap-backend/static
      expose: 
        - "8000"
      secrets:
        - source: backend_admin_name
          target: admin_name
        - source: backend_admin_email
          target: admin_email
        - source: backend_admin_password
          target: back_admin_password
        - db_password
        - db_username
        - backend_django_secret
        - client_id
        - client_secret
      environment:
        - "MIGRATION=${MIGRATION}"
        - "DEBUG=false"
    
    frontend:
      build:
        context: .
        dockerfile: docker/Dockerfile-frontend
      expose:
        - "4200"
    
    nginx:
      build:
        context: .
        dockerfile: docker/Dockerfile-nginx
      depends_on:
        - backend
      volumes:
        - static_backend:/etc/backend/static
      ports:
        - "80:80"
        - "443:443"

secrets:
  iotcore_admin_name:
    file: ./secrets/iotcore_admin_name
  iotcore_admin_email:
    file: ./secrets/iotcore_admin_email
  iotcore_admin_password:
    file: ./secrets/iotcore_admin_password
  backend_admin_name:
    file: ./secrets/backend_admin_name
  backend_admin_email:
    file: ./secrets/backend_admin_email
  backend_admin_password:
    file: ./secrets/backend_admin_password
  db_username:
    file: ./secrets/db_username
  db_password:
    file: ./secrets/db_password
  iotcore_django_secret:
    file: ./secrets/iotcore_django_secret
  backend_django_secret:
    file: ./secrets/backend_django_secret
  client_id:
    file: ./secrets/client_id
  client_secret:
    file: ./secrets/client_secret

volumes:
  static_backend:
  pg_data:
