# Generated by Django 2.2 on 2021-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dev_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='public',
        ),
        migrations.RemoveField(
            model_name='device',
            name='users',
        ),
        migrations.RemoveField(
            model_name='location',
            name='users',
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='data_typ',
            field=models.TextField(choices=[('b', 'Bool'), ('f', 'Float'), ('dt', 'DateTime')], default='b'),
        ),
        migrations.AddField(
            model_name='device',
            name='typ',
            field=models.TextField(choices=[('i', 'Input'), ('o', 'Output'), ('m', 'Memory')], default='i'),
        ),
    ]
