# Generated by Django 2.2 on 2021-03-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210301_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='timeeventlabel',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
