# Generated by Django 2.2 on 2021-03-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_capability_timeeventlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='time_val',
            field=models.IntegerField(null=True),
        ),
    ]
