# Generated by Django 2.2 on 2021-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_trigger_time_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='mode',
            field=models.TextField(choices=[('c', 'Control'), ('sf', 'Syn_feedback'), ('nf', 'Nosyn_feedback'), ('sn', 'Syn_nofeedback'), ('nn', 'Nosyn_nofeedback')], default='c', null=True),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
