# Generated by Django 2.2 on 2021-07-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210425_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('string', 'string'), ('number', 'number'), ('vector3', 'vector3'), ('enum', 'enum'), ('dynamic_enum', 'dynamic_enum'), ('color_map', 'color_map'), ('json_object', 'json_object'), ('date', 'date')], default='string', max_length=13)),
                ('cap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Capability')),
                ('dev', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Device')),
                ('loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
                ('param', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Parameter')),
            ],
        ),
    ]
