# Generated by Django 2.2 on 2021-07-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210727_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('image', models.TextField(blank=True, max_length=128, null=True)),
                ('title', models.TextField(blank=True, max_length=128, null=True)),
                ('needcondition', models.BooleanField(default=False)),
                ('showrules', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Scenario')),
            ],
        ),
    ]
