# Generated by Django 2.2 on 2021-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_scenariopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemonitor',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
    ]
