# Generated by Django 2.2 on 2021-07-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_devicemonitor_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentruleact', to='backend.ESRule'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentruletrig', to='backend.ESRule'),
        ),
    ]
