# Generated by Django 2.2 on 2021-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_scenariopage_isimpfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariopage',
            name='isexperience',
            field=models.BooleanField(default=False),
        ),
    ]
