# Generated by Django 2.2 on 2021-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_scenariopage_isexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pending_trace',
            field=models.BooleanField(default=False),
        ),
    ]
