# Generated by Django 2.2 on 2022-02-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_location_pending_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
